
name: Prepare release and publish package to NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
      - uses: actions/setup-node@v2
        with:
          node-version: '12'      
      - run: npm install
      - name: Test
      - run: npm test
      - name: Build
      - run: npm run build
  
  release:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run automated release process with semantic-release
        if: github.event_name == 'push'
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
